languageCode = "en-us"
title = "Ethan Martin"

theme = "hugo-coder"

pygmentsStyle = "xcode"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
    author = "Ethan Martin"
    info = "Software engineer. Tech enthusiast. Mediocre trumpeter."
    description = "Ethan Martin's personal website and blog."
    avatarurl = "images/portrait.jpg"

    colorScheme = "light"
    hideColorSchemeToggle = "true"

    maxSeeAlsoItems = 5

[taxonomies]
    tag = "tags"
    category = "categories"

[[params.social]]
    name = "GitHub"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/emar10/"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 1
    url = "mailto:ethan@emar10.dev"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 1
    url = "https://linkedin.com/in/ethan-martin/"

[params.plausibleAnalytics]
    domain = "emar10.dev"
    serverURL = "oracle.emar10.dev"

[[menu.main]]
    name = "Posts"
    weight = 1
    url = "/posts/"

[[menu.main]]
    name = "Tags"
    weight = 2
    url = "/tags/"
