name: Build and publish OCI image to GHCR

on:
  push:
    branches: main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build image with Buildah
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: emar10.dev
          containerfiles: ./Containerfile
          tags: ${{ github.sha }} latest

      - name: Login to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/emar10
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io/emar10

